-- AlterTable
ALTER TABLE "Measurement" ADD COLUMN     "micsCoPpm" DOUBLE PRECISION,
ADD COLUMN     "micsNh3Ppm" DOUBLE PRECISION,
ADD COLUMN     "micsNo2Ppb" DOUBLE PRECISION,
ADD COLUMN     "so2Ppb" DOUBLE PRECISION;
